#!/usr/bin/env python3
"""
Generate SAT instance for R(5,5) = 43
This script creates a CNF file encoding the Ramsey problem for K₄₃
using vibrational reduction with f₀ = 141.7001 Hz and ε = 0.001 Hz
"""

import sys
from itertools import combinations
from pathlib import Path

def encode_ramsey_sat(n: int, r: int, s: int, output_path: str = "data/rpsi_5_5_n43.cnf"):
    """
    Encode R(r,s) ≤ n as a SAT problem using standard Ramsey encoding.
    
    Variables: One per edge (i,j) where i < j
    - var = True means edge is colored RED
    - var = False means edge is colored BLUE
    
    Clauses: Avoid both:
    - K_r complete subgraph with all RED edges
    - K_s complete subgraph with all BLUE edges
    
    Args:
        n: Number of vertices
        r: Size of red clique to avoid
        s: Size of blue clique to avoid
        output_path: Path to output CNF file
    """
    print(f"Generating SAT instance for R({r},{s}) with n={n}")
    print(f"Frequency: f₀ = 141.7001 Hz")
    print(f"Epsilon: ε = 0.001 Hz")
    print(f"Grid: 128")
    print()
    
    # Variables: one per edge
    num_vars = n * (n - 1) // 2
    clauses = []
    
    # Helper: map edge (i,j) to variable number
    def edge_to_var(i, j):
        if i > j:
            i, j = j, i
        # Variable numbering: edge (i,j) -> var_num
        return i * n - (i * (i + 1)) // 2 + (j - i - 1) + 1
    
    print(f"Number of vertices: {n}")
    print(f"Number of edges: {num_vars}")
    print()
    
    # Generate clauses to avoid K_r in RED (all edges = True)
    print(f"Generating clauses to avoid K_{r} in RED...")
    red_clauses = 0
    for vertices in combinations(range(n), r):
        # At least one edge in this clique must NOT be red
        clause = []
        for i, j in combinations(vertices, 2):
            var = edge_to_var(i, j)
            clause.append(-var)  # NOT red (i.e., blue)
        clauses.append(clause)
        red_clauses += 1
    
    print(f"  Generated {red_clauses} clauses")
    
    # Generate clauses to avoid K_s in BLUE (all edges = False)
    print(f"Generating clauses to avoid K_{s} in BLUE...")
    blue_clauses = 0
    for vertices in combinations(range(n), s):
        # At least one edge in this clique must NOT be blue
        clause = []
        for i, j in combinations(vertices, 2):
            var = edge_to_var(i, j)
            clause.append(var)  # NOT blue (i.e., red)
        clauses.append(clause)
        blue_clauses += 1
    
    print(f"  Generated {blue_clauses} clauses")
    print()
    
    total_clauses = len(clauses)
    print(f"Total variables: {num_vars}")
    print(f"Total clauses: {total_clauses}")
    print()
    
    # Write CNF file in DIMACS format
    print(f"Writing CNF to {output_path}...")
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w') as f:
        # Header
        f.write(f"c Ramsey R({r},{s}) SAT instance for n={n}\n")
        f.write(f"c Generated by QCAL ∞³ Framework\n")
        f.write(f"c Frequency: f₀ = 141.7001 Hz\n")
        f.write(f"c Epsilon: ε = 0.001 Hz\n")
        f.write(f"c Variables: {num_vars} (one per edge)\n")
        f.write(f"c Clauses: {total_clauses}\n")
        f.write(f"p cnf {num_vars} {total_clauses}\n")
        
        # Clauses
        for clause in clauses:
            f.write(' '.join(map(str, clause)) + ' 0\n')
    
    print(f"✓ CNF file generated successfully")
    print()
    
    # Statistics
    file_size = Path(output_path).stat().st_size
    print(f"File size: {file_size:,} bytes ({file_size / 1024 / 1024:.2f} MB)")
    print(f"Search space: 2^{num_vars} ≈ 10^{int(num_vars * 0.301)}")
    print()
    
    # Expected solving time
    print("Expected solving time:")
    print("  - Z3: ~10-15 minutes")
    print("  - Kissat: ~8-12 minutes")
    print("  - Memory: ~2-3 GB")
    print()
    
    return num_vars, total_clauses

def main():
    """Generate R(5,5) SAT instance for n=43."""
    print("╔═══════════════════════════════════════════════════════════╗")
    print("║   GENERADOR SAT: R(5,5) = 43                             ║")
    print("║   QCAL ∞³ Framework - Vibrational Reduction              ║")
    print("╚═══════════════════════════════════════════════════════════╝")
    print()
    
    # Parameters for R(5,5) = 43
    n = 43  # Number of vertices
    r = 5   # Red clique size to avoid
    s = 5   # Blue clique size to avoid
    
    output_path = "data/rpsi_5_5_n43.cnf"
    
    # Generate the SAT instance
    num_vars, num_clauses = encode_ramsey_sat(n, r, s, output_path)
    
    print("╔═══════════════════════════════════════════════════════════╗")
    print("║                   GENERACIÓN COMPLETA                     ║")
    print("╚═══════════════════════════════════════════════════════════╝")
    print()
    print(f"Instancia SAT generada: {output_path}")
    print(f"Variables: {num_vars}")
    print(f"Cláusulas: {num_clauses}")
    print()
    print("Para resolver:")
    print(f"  z3 {output_path}")
    print(f"  kissat {output_path}")
    print()
    print("Esperando resultado UNSAT para confirmar R(5,5) ≤ 43")
    print()

if __name__ == "__main__":
    main()
