#!/bin/bash
# Verify LRAT certificate for Rψ(5,5) proof
#
# This script uses lrat-check or drat-trim to verify the LRAT certificate
# generated by a SAT solver (e.g., Kissat, CaDiCaL).
#
# Usage:
#   ./verify_lrat.sh [cnf_file] [lrat_file]
#   ./verify_lrat.sh ../data/rpsi_5_5_n16.cnf ../cert/rpsi_5_5_n16.lrat
#
# Author: José Manuel Mota Burruezo (JMMB Ψ✧∴)
# Frecuencia: 141.7001 Hz - Campo QCAL ∞³

set -e

# Default files
CNF_FILE="${1:-../data/rpsi_5_5_n16.cnf}"
LRAT_FILE="${2:-../cert/rpsi_5_5_n16.lrat}"

# Check if files exist
if [ ! -f "$CNF_FILE" ]; then
    echo "Error: CNF file not found: $CNF_FILE"
    echo "Usage: $0 [cnf_file] [lrat_file]"
    exit 1
fi

if [ ! -f "$LRAT_FILE" ]; then
    echo "Error: LRAT file not found: $LRAT_FILE"
    echo "Please generate LRAT certificate first with Kissat or CaDiCaL"
    exit 1
fi

echo "════════════════════════════════════════════════════════"
echo "  Verifying LRAT Certificate for Rψ(5,5)"
echo "════════════════════════════════════════════════════════"
echo "CNF File: $CNF_FILE"
echo "LRAT File: $LRAT_FILE"
echo "Timestamp: $(date -Iseconds)"
echo ""

# Get file info
CNF_SIZE=$(du -h "$CNF_FILE" | cut -f1)
LRAT_SIZE=$(du -h "$LRAT_FILE" | cut -f1)

echo "File Sizes:"
echo "  CNF: $CNF_SIZE"
echo "  LRAT: $LRAT_SIZE"
echo ""

# Try to find LRAT checker
CHECKER=""
if command -v lrat-check &> /dev/null; then
    CHECKER="lrat-check"
elif command -v drat-trim &> /dev/null; then
    CHECKER="drat-trim"
else
    echo "Error: No LRAT/DRAT checker found"
    echo ""
    echo "Please install one of:"
    echo "  - lrat-check: https://github.com/marijnheule/drat-trim"
    echo "  - drat-trim: https://github.com/marijnheule/drat-trim"
    echo ""
    exit 1
fi

echo "Using checker: $CHECKER"
echo "────────────────────────────────────────────────────────"

# Run verification
START_TIME=$(date +%s)
if [ "$CHECKER" = "lrat-check" ]; then
    if lrat-check "$CNF_FILE" "$LRAT_FILE"; then
        RESULT="VALID"
        EXIT_CODE=0
    else
        RESULT="INVALID"
        EXIT_CODE=$?
    fi
else
    # drat-trim
    if drat-trim "$CNF_FILE" "$LRAT_FILE"; then
        RESULT="VALID"
        EXIT_CODE=0
    else
        RESULT="INVALID"
        EXIT_CODE=$?
    fi
fi
END_TIME=$(date +%s)
ELAPSED=$((END_TIME - START_TIME))

echo "────────────────────────────────────────────────────────"
echo ""
echo "Result: $RESULT"
echo "Time: ${ELAPSED}s"
echo ""

if [ "$RESULT" = "VALID" ]; then
    echo "✓ SUCCESS: LRAT certificate is VALID"
    echo ""
    echo "  The proof has been independently verified by $CHECKER"
    echo "  This confirms: Rψ(5,5) ≤ 16"
    echo ""
    exit 0
else
    echo "✗ FAILURE: LRAT certificate is INVALID"
    echo ""
    echo "  The certificate could not be verified!"
    echo "  Please regenerate the certificate."
    echo ""
    exit 1
fi
